[package]
name = "solana-hamt"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.6.9"
thiserror = "1.0.24"
arrayref = "0.3.6"
borsh = "0.9.1"

[lib]
crate-type = ["cdylib", "lib"]
